language: python
python:
  - "2.7"
install:
  - python setup.py install
  - pip install codecov pytest-cov
script: py.test --cov=./
after_success:
  codecov
notifications:
  email: false
  slack: realfastvla:oIyoiLcRdeYEif8kh7tANDKC