language: python
python:
  - "2.7"
install:
  - python setup.py install
  - pip install codecov pytest-cov
before_script:
  - git config --global user.email "caseyjlaw@gmail.com"
  - git config --global user.name "Travis-CI"
script: py.test --cov=./
after_success:
  codecov
notifications:
  email: false
  slack: realfastvla:oIyoiLcRdeYEif8kh7tANDKC