language: python
python:
  - "2.7"
install:
  - pip install codecov coverage
  - python setup.py install
before_script:
  - git config --global user.email "caseyjlaw@gmail.com"
  - git config --global user.name "Travis-CI"
script: py.test
after_success:
  - coverage run --source activegit -m py.test
  - codecov
notifications:
  email: false
  slack: realfastvla:oIyoiLcRdeYEif8kh7tANDKC